# Getting started with PyTorch

Content based on tutorial provided by PyTorch on this [page](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [92]:
import torch
import numpy as np
from __future__ import print_function

# First introduction to PyTorch
---
## Tensors
---
### Construction of tensors


Construct a 5x3 empty matrix

In [5]:
torch.empty(5, 3)

tensor([[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -6.3615e+03]])

Construct a 5x3 random matrix

In [6]:
torch.rand(5, 3)

tensor([[0.3216, 0.8210, 0.6454],
        [0.5143, 0.0978, 0.5250],
        [0.5089, 0.8549, 0.4559],
        [0.0646, 0.0031, 0.0113],
        [0.7410, 0.1946, 0.1348]])

Construct a 5x3 matrix of zeros, with dtype torch.long

In [7]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Construct a tensor from data (array)

In [25]:
x = torch.tensor([5.5, 3])

Construct a tensor based on an existing tensor -> will resuse properties like dtype

In [26]:
x.dtype

torch.float32

In [27]:
x = x.new_ones(5, 3)
x.dtype

torch.float32

In [28]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
x = x.new_ones(5, 3, dtype=torch.double)
x.dtype

torch.float64

Construct a tensor based on an existing vector -> will reuse shape

In [30]:
x = torch.randn_like(x, dtype=torch.float)

In [33]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [35]:
x.size()

torch.Size([5, 3])

In [36]:
x.shape

torch.Size([5, 3])

### Operations


In [42]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [43]:
y = torch.rand(5,3)

In [44]:
y

tensor([[0.0436, 0.7935, 0.5893],
        [0.4077, 0.7985, 0.0950],
        [0.3106, 0.0820, 0.8981],
        [0.6567, 0.8187, 0.4716],
        [0.4245, 0.9169, 0.7377]])

Addition: syntax 1

In [45]:
x+y

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: syntax 2

In [47]:
torch.add(x, y)

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: providing an output tensor as argument 

In [50]:
result = torch.empty_like(x)
torch.add(x, y, out=result)
result

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: in-place

In [53]:
y.add_(x)
y

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Any operation that mutates a tensor in-place is post-fixed with an `_`. 

For example: `x.copy_(y)`, `x.t_()`, will change `x`.

### Indexing


In [56]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [54]:
x[:,1]

tensor([ 1.0400, -1.0068, -0.5140, -0.4124, -1.1577])

In [55]:
x[1,:]

tensor([-1.0377, -1.0068,  0.6891])

### Resizing


In [70]:
x = torch.randn(4, 4)
x

tensor([[-1.1969,  1.0433,  0.7137,  0.4110],
        [-0.4940, -0.2193,  0.5760, -0.1723],
        [ 2.1318, -0.2729,  0.6299, -0.8904],
        [ 2.3227, -0.2843, -0.3562,  1.8049]])

In [71]:
y = x.view(16)
y

tensor([-1.1969,  1.0433,  0.7137,  0.4110, -0.4940, -0.2193,  0.5760, -0.1723,
         2.1318, -0.2729,  0.6299, -0.8904,  2.3227, -0.2843, -0.3562,  1.8049])

In [72]:
z = x.view(-1, 8)
z

tensor([[-1.1969,  1.0433,  0.7137,  0.4110, -0.4940, -0.2193,  0.5760, -0.1723],
        [ 2.1318, -0.2729,  0.6299, -0.8904,  2.3227, -0.2843, -0.3562,  1.8049]])

In [74]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [83]:
x = torch.randn(1)
x

tensor([-1.6694])

When tensor has only one element, use `.item()` to get value as a Python number

In [84]:
x.item()

-1.669400691986084

## Numpy Bridge
---
### Converting a Torch tensor to a NumPy Array

In [85]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [87]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [88]:
print(type(a), type(b))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [89]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [90]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

**Remark : change in a will affect b**

### Converting NumPy array to Torch Tensor

In [93]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [94]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

**Remark : change in a will affect b as well**

## CUDA Tensors
---

In [99]:
x = torch.rand(5, 3)
x

tensor([[0.8448, 0.0389, 0.0192],
        [0.2282, 0.8934, 0.1205],
        [0.4802, 0.5128, 0.5499],
        [0.3310, 0.3655, 0.7399],
        [0.2664, 0.2544, 0.5427]])

In [102]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", dtype=torch.double))

tensor([[1.8448, 1.0389, 1.0192],
        [1.2282, 1.8934, 1.1205],
        [1.4802, 1.5128, 1.5499],
        [1.3310, 1.3655, 1.7399],
        [1.2664, 1.2544, 1.5427]], device='cuda:0')
tensor([[1.8448, 1.0389, 1.0192],
        [1.2282, 1.8934, 1.1205],
        [1.4802, 1.5128, 1.5499],
        [1.3310, 1.3655, 1.7399],
        [1.2664, 1.2544, 1.5427]], dtype=torch.float64)


---

# Autograd

---

## Tensors

---

Attributes `.requires_grad` as `True` : tracks all operation on the tensor.

Method `.backward()` : to have all the gradients computed automatically.

Gradients are accumulated into the `.grad` attribute.

---

To stop a tensor from tracking history, call `.detach()` function to detach it from the computation history and prevent future computation from being tracked

Another way is to wrap the code block in ` with torch.n_grad():`

---
Another important class for autograd implementation : `Function`.

`Tensor` and `Function` are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a `.grad_fn` attribute that references a `Function` that has created the `Tensor` (except for Tensors creates by the user - their `grad_fn` is `None`).

---

If you want to compute the derivatives, you can call `.backward()` on a `Tensor`. If `Tensor` is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to `backward()`, however if it has more elements, you need to specify a `gradient` argument that is a tensor of matching shape.


In [107]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [108]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [110]:
y.grad_fn

In [115]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


`.requires_grad_( ... )` changes an existing Tensor\'s `requires_grad` flag in-place. The input flag defaults to `False` if not given.

In [121]:
a = torch.randn(2, 2)
a = (a * 3) / (a - 1)
a.requires_grad

False

In [122]:
a.requires_grad_(True)
a.requires_grad

True

In [124]:
b = (a * a).sum()
print(b.requires_grad)
print(b.grad_fn)

True
