# Getting started with PyTorch

Content based on tutorial provided by PyTorch on this [link](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [2]:
import torch
from __future__ import print_function

## Tensors

### Construction of tensors

Construct a 5x3 empty matrix

In [5]:
torch.empty(5, 3)

tensor([[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -6.3615e+03]])

Construct a 5x3 random matrix

In [6]:
torch.rand(5, 3)

tensor([[0.3216, 0.8210, 0.6454],
        [0.5143, 0.0978, 0.5250],
        [0.5089, 0.8549, 0.4559],
        [0.0646, 0.0031, 0.0113],
        [0.7410, 0.1946, 0.1348]])

Construct a 5x3 matrix of zeros, with dtype torch.long

In [7]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Construct a tensor from data (array)

In [25]:
x = torch.tensor([5.5, 3])

Construct a tensor based on an existing tensor -> will resuse properties like dtype

In [26]:
x.dtype

torch.float32

In [27]:
x = x.new_ones(5, 3)
x.dtype

torch.float32

In [28]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
x = x.new_ones(5, 3, dtype=torch.double)
x.dtype

torch.float64

Construct a tensor based on an existing vector -> will reuse shape

In [30]:
x = torch.randn_like(x, dtype=torch.float)

In [33]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [35]:
x.size()

torch.Size([5, 3])

In [36]:
x.shape

torch.Size([5, 3])

### Operations

In [42]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [43]:
y = torch.rand(5,3)

In [44]:
y

tensor([[0.0436, 0.7935, 0.5893],
        [0.4077, 0.7985, 0.0950],
        [0.3106, 0.0820, 0.8981],
        [0.6567, 0.8187, 0.4716],
        [0.4245, 0.9169, 0.7377]])

Addition: syntax 1

In [45]:
x+y

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: syntax 2

In [47]:
torch.add(x, y)

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: providing an output tensor as argument 

In [50]:
result = torch.empty_like(x)
torch.add(x, y, out=result)
result

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

Addition: in-place

In [53]:
y.add_(x)
y

tensor([[ 0.3651,  1.8335,  0.8655],
        [-0.6299, -0.2083,  0.7841],
        [-1.3428, -0.4320,  0.7643],
        [ 2.0750,  0.4062,  0.6638],
        [-1.1536, -0.2408, -0.1691]])

> Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

### Indexing

In [56]:
x

tensor([[ 0.3215,  1.0400,  0.2762],
        [-1.0377, -1.0068,  0.6891],
        [-1.6534, -0.5140, -0.1338],
        [ 1.4183, -0.4124,  0.1923],
        [-1.5781, -1.1577, -0.9068]])

In [54]:
x[:,1]

tensor([ 1.0400, -1.0068, -0.5140, -0.4124, -1.1577])

In [55]:
x[1,:]

tensor([-1.0377, -1.0068,  0.6891])